service: pants-lambda

frameworkVersion: "3"

plugins:
  - serverless-better-credentials

package:
  individually: true

provider:
  name: aws
  runtime: python3.9
  region: eu-west-2

functions:
  hello:
    handler: lambda.handler.handle
    package:
      artifact: ../../dist/src.lambda/main.pex
    layers:
      - ${ssm:/pants-layer/numpy/latest}
